version: "3.9"
services:
  backend:
    build:
      context: ./langbridge
      dockerfile: Dockerfile
    container_name: langbridge-backend
    env_file:
      - ./langbridge/.env
    environment:
      ENVIRONMENT: development
      BACKEND_URL: http://langbridge.test.com/api
      FRONTEND_URL: http://langbridge.test.com
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: langbridge
      POSTGRES_PASSWORD: langbridge
      POSTGRES_DB: langbridge
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - web
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://langbridge.test.com
    container_name: langbridge-client
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://langbridge.test.com
      PORT: 3000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - web
  db:
    image: postgres:16-alpine
    container_name: langbridge-db
    environment:
      POSTGRES_USER: langbridge
      POSTGRES_PASSWORD: langbridge
      POSTGRES_DB: langbridge
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langbridge"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - web
  redis:
    image: redis:7-alpine
    container_name: langbridge-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: langbridge-proxy
    environment:
      PROXY_LISTEN_HOST: "0.0.0.0"
      PROXY_PG_PORT: 55432
      PROXY_MYSQL_PORT: 53306
    ports:
      - "55432:55432"
      - "53306:53306"
    depends_on:
      - db
      - redis
    networks:
      - web
volumes:
  pg_data:
  redis_data:

networks:
  web:
    external: true
