version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: trino-postgres
    environment:
      POSTGRES_USER: trino
      POSTGRES_PASSWORD: trino
      POSTGRES_DB: customersdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trino -d customersdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mysql:
    image: mysql:8.0
    container_name: trino-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: trino
      MYSQL_DATABASE: ordersdb
      MYSQL_USER: trino
      MYSQL_PASSWORD: trino
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -ptrino"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  trino:
    image: trino:479-SNAPSHOT-amd64
    container_name: trino-coordinator
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ../trino/plugin/trino-postgresql/target/trino-postgresql-479-SNAPSHOT:/usr/lib/trino/plugin/postgresql:ro
      # - ../trino/plugin/trino-mysql/target/trino-mysql-479-SNAPSHOT:/usr/lib/trino/plugin/mysql:ro
      # - ../trino/plugin/trino-base-jdbc/target/trino-base-jdbc-479-SNAPSHOT :/usr/lib/trino/plugin/trino-base-jdbc:ro
      - ./trino/catalog:/etc/trino/catalog:ro
      - ./trino/etc/config.properties:/etc/trino/config.properties:ro
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
